### ISSUE TITLE
AlleyCatHouse house show

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/chill_out#10]
Great chill-out day Saturday (code-free!) followed by first-ever house show at AlleyCatHouse -- 3 bands, nice crowd, good vibes.

AlleyCat chilling before the show
![alleycat_pre1](https://cloud.githubusercontent.com/assets/10157094/9028195/1823d374-393e-11e5-9dea-55cf34cbeba6.jpg)

This is the place...
![achouse_sign1](https://cloud.githubusercontent.com/assets/10157094/9028191/edcb90c6-393d-11e5-85b7-25a6e456b56c.jpg)

The scene in the kitchen/living room/dining room...
![crowd_brkpssn1](https://cloud.githubusercontent.com/assets/10157094/9028192/f5c50f1e-393d-11e5-8a5f-efef06afaa3b.jpg)

Show Pony kicks it off...
![showpony_2](https://cloud.githubusercontent.com/assets/10157094/9028236/b1b00bec-393f-11e5-95eb-9761312b6ec9.jpg)

More Show Pony... amazing set of intricate rhythms and tight transitions...
![showpony1](https://cloud.githubusercontent.com/assets/10157094/9028193/fc3a64d4-393d-11e5-8d42-a9cca9f4b96a.jpg)

**Comment by RobertAKARobin** [comment]
Way to go, Tom! Cute cat!
