### ISSUE TITLE
Domo Arigato Mr. Roboto

### ISSUE THREAD

**Issue by karldonus** [ga-dc/chill_out#2]
On Friday night, I binged Watched Mr. Robot. Then I had a glorious 12 hours of sleep -- needless to say, the highlight of my weekend. After my best friend said goodbye to his girlfriend (who will be teaching English in Japan for the next year), I took him out for brunch at Ted's Bulletin to cheer him up. Afterward, we watched Mission Impossible. In the late afternoon, I test drove my parents first brand new car in 40-some years -- a Subaru impreza. At night, I watched the first few episodes of Sense8 -- a netflix original series.

**Comment by RobertAKARobin** [comment]
Mm, those house-made pop tarts.
