### ISSUE TITLE
Beach!

### ISSUE THREAD

**Issue by Curtismn87** [ga-dc/chill_out#21]
![img_1597](https://cloud.githubusercontent.com/assets/12704687/9029360/750a4a1a-3960-11e5-9a6b-572a20abeaa1.JPG)
![img_1591](https://cloud.githubusercontent.com/assets/12704687/9029364/7c9a6940-3960-11e5-9203-447420660616.JPG)

**Comment by RobertAKARobin** [comment]
If you pay me $5 I _won't_ Slack out this picture to the group.
