### ISSUE TITLE
Chilled briefly  

### ISSUE THREAD

**Issue by M00staff** [ga-dc/chill_out#26]
Comfort 5 
Completeness 4

Did a little dance, made a little love, pretty much got down. 

Went to the GA happy hour, saw a movie in the park, went to the gym, drank whiskey on the porch of an old friend that's trying to get me a job - and found a sweet new Disco Biscuits video https://www.youtube.com/watch?v=CQuwfsXB8cI (the jam sequence starts at 3:45)

**Comment by RobertAKARobin** [comment]
Someone should make a song out of that.
