### ISSUE TITLE
Erica Andersen's Chill Out Homework

### ISSUE THREAD

**Issue by ericacomfort** [ga-dc/chill_out#28]
Comfort: 5/5
Completeness: 5/5

I thoroughly enjoyed the assignment to Chill Out! I started my Saturday by spending a few hours in the sunshine at the pool. I caught up on reading 'Game of Thrones' which was really nice. For lunch, I grilled some awesome salmon and veggies. To top off the day, I went to the Rock and Roll Hotel on H Street for dinner and to check out the band, 'Broke Royals'. The band was great and so were the strawberry daiquiris. This assignment was so much fun!

**Comment by RobertAKARobin** [comment]
Mm, daiquiris.
