### ISSUE TITLE
Chill Out

### ISSUE THREAD

**Issue by silviascript** [ga-dc/chill_out#36]
Comfort Level: 3/5 - 5/5
Completeness: -1/5

I attended Startup Weekend to meet new connections, test my design skills, and to contribute to a team with an interesting product. Our team created an iPhone application that collected all the user's notifications from various media services, such as news, to reduce noise. 

The user would only receive notifications that fit their interests. For example, if I only wanted to receive notifications from the New York Times, the Washington Post, and NPR about a certain topic, the application would gather all articles about that topic. Then, the application would only send one notification at a desired time that I found convenient.

My sleep schedule has been affected, but that is alright. I left during Happy Hour and worked at Washington Post until 1:00am, and continued working to 4:00am at home. Woke up at 7:00am, returned at 8:30am, left at 11:30pm, and continued working to 6:30am at home. Returned at 8:30am and left at 9:00pm. I was committed to my team and the product, I designed the UX and UI with a young designer, he designed the logo, and we had the best designed application of the hackathon.

Unfortunately, we did not place; however, I accomplished my goal at designing a clean user interface and experience for the iPhone application. I mostly concentrated on my UX and UI skills, instead of development, in order to strategize my second project better. Overall, it was fun, yet an exhausting experience. Would I attend another one? Yes.

I should do this...

![Bye, computer!](http://cl.ly/c84y/silly_computer.gif)

But, I didn't.

**Comment by RobertAKARobin** [comment]
I hope you at least had fun, and feel satisfied with what you accomplished!
