### ISSUE TITLE
Chill Out

### ISSUE THREAD

**Issue by robertbenjamin** [ga-dc/chill_out#48]
Sorry for not submitting this earlier, didn't realize when it was due!

This weekend, I slept in nice and late on Saturday, headed over to the library to find some books to read and ended up borrowing a book called Prague (the story's set in Budapest, ironically) by Arthur Phillips. I stopped by KFC on my way back because I had been craving it for awhile for some reason, immediately regretted eating there. That night I watched the tv show Mr. Robot with some friends.

**Comment by nolds9** [comment]
:+1:
