### ISSUE TITLE
Chill Out

### ISSUE THREAD

**Issue by pdoulatshahi** [ga-dc/chill_out#5]
Friday - after class, I hosted a happy hour for the company I teach French for. I caught up with some former students who attended, which was great.

Saturday - I teach a French class from 9-1 on Saturdays, so I went to bed very early on Friday. After French class, I went to yoga with a friend - afterwards, we went to The Pig for happy hour. I spent the night in watching Wet Hot American Summer: First Day of Camp and some Seinfeld on Hulu.

I did yoga again this morning, and I might go watch MI5 later. A very relaxing weekend - much appreciated! Looking forward to hitting the ground running tomorrow morning.

**Comment by RobertAKARobin** [comment]
Bien fait!
