### ISSUE TITLE
Fun Weekend Stuff!

### ISSUE THREAD

**Issue by ghost** [ga-dc/chill_out#7]
Comfort: 3/5
Completeness: 4.5/5

My cousin got married this weekend so that was fun. My parents came in for the weekend so I spent quite a bit of time with them hanging out and eating a ton of food.

We had an amazing meal Saturday night for the Rehearsal dinner and then ate a bunch the day of the wedding. I got my groove on out on the dance floor for longer than I should have. Overall, a solid, relaxing, weekend with the fam!

**Comment by RobertAKARobin** [comment]
Congrats to your cousin!
