### ISSUE TITLE
QT w/a New Friend

### ISSUE THREAD

**Issue by kristingreenslit** [ga-dc/chill_out#9]
Comfort: 5
Completeness: 5

I really appreciated this assignment, although it was hard for me to spend 24 hours not coding b/c I really enjoy it. I used the spare time to reconnect with a few friends from home (I moved to D.C. last month for WDI), as well as catch up on a few episodes of The Good Wife with my new friend Sydnie:

https://drive.google.com/file/d/0B7OGbeW8U2_8RlR5Q2xlRGw1VHM/view?usp=sharing

**Comment by RobertAKARobin** [comment]
Is Sydnie single? She has a cute face.

**Comment by kristingreenslit** [comment]
Robin: She is single! :)
